### PR TITLE
rpassword prompt

### PR DESCRIPTION
**Pull request by ravidio**

### CODE REVIEW

**Comment by ravidio** [comment]
(fixes #69)

**Comment by mably** [comment]
Looks like it doens't handle my empty password 😱

**Comment by keymone** [comment]
@mably does it fail to unlock? or do you mean that it asks for password even if it's blank?

**Comment by mably** [comment]
It fails to unlock: `ERROR: could not unlock wallet! are you using the correct passphrase?`

**Comment by keymone** [comment]
here's my exchange with wallet713:

```
Unlock your existing wallet or type `init` to initiate a new one
Use `listen` to connect to grinbox or `help` to see available commands

wallet713> init
Password:
Your recovery phrase is:

credit cable valve festival toilet grant carry lecture object essay bind exotic suggest system hurry luxury correct hundred giant lake amount peasant increase clever

Please back-up these words in a non-digital format.
Your grinbox address: gVw9N9jXYd6R35cj2WEAw9XAafC3CR4JpCDFjYhG9ToJVuk9mbxx
WARNING: wallet with no passphrase.
wallet713> exit
~ % wallet713

Welcome to wallet713

Your grinbox address: gVw9N9jXYd6R35cj2WEAw9XAafC3CR4JpCDFjYhG9ToJVuk9mbxx
Use `listen` to connect to grinbox or `help` to see available commands

wallet713> unlock
Password:
ERROR: wallet already unlocked
wallet713> lock
```

**Comment by keymone** [comment]
i think @ravidio has made some additional modifications, at least "Password:" prompt has changed to "passphrase:"

**Pull request merged**
